export {default as Home} from "./Home"
export {default as Trepcismo} from "./Trepcismo"
export {default as Sobre} from "./Sobre"
export {default as Galeria} from "./Galeria"
export {default as Faqpage} from "./Faq"